import type * as React from "react";
import type { useRouter } from "next/navigation";
import type { Hotel } from "@/features/hotels/types/hotel.types";
import type { Client } from "@/features/clients/types/client.types";
import type { Consultant } from "@/features/consultants/types/consultant.types";
import type { Destination } from "@/features/destinations/types/destination.types";
import type { DayItineraryItem } from "../components/builder-steps/step-2-itinerary";

export interface PackageBuilderHookState {
  router: ReturnType<typeof useRouter>;
  step: 1 | 2 | 3 | 4;
  setStep: (step: 1 | 2 | 3 | 4) => void;
  isPkgLoading: boolean;
  packageName: string;
  setPackageName: (val: string) => void;
  clientId: string;
  setClientId: (val: string) => void;
  destinationId: string;
  setDestinationId: (val: string) => void;
  startDate: string;
  setStartDate: (val: string) => void;
  numberOfDays: number;
  handleNumberOfDaysChange: (count: number) => void;
  adults: number;
  setAdults: (val: number) => void;
  childrenCount: number;
  setChildrenCount: (val: number) => void;
  status: "CONFIRMED" | "CANCELLED";
  setStatus: (val: "CONFIRMED" | "CANCELLED") => void;
  activeDay: number;
  setActiveDay: (day: number) => void;
  daysData: DayItineraryItem[];
  setDaysData: React.Dispatch<React.SetStateAction<DayItineraryItem[]>>;
  consultantId: string;
  setConsultantId: (id: string) => void;
  clients: Client[];
  destinations: Destination[];
  consultants: Consultant[];
  hotels: Hotel[];
  isSubmitting: boolean;
  handleStepClick: (targetStep: number) => void;
  handleSubmitPackage: () => Promise<void>;
}
